=== mathoshek/Dbc2MySQL/src/Structure.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="DBFilesClient">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="table" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="field" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="type" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="int8"/>
                        <xs:enumeration value="uint8"/>
                        <xs:enumeration value="int16"/>
                        <xs:enumeration value="uint16"/>
                        <xs:enumeration value="int32"/>
                        <xs:enumeration value="uint32"/>
                        <xs:enumeration value="int64"/>
                        <xs:enumeration value="uint64"/>
                        <xs:enumeration value="float"/>
                        <xs:enumeration value="double"/>
                        <xs:enumeration value="string"/>
                        <xs:enumeration value="loc"/>
                        <xs:enumeration value="ignored"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="comment" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="primary" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mathoshek/Dbc2MySQL/src/StructureCata.xml
<?xml version="1.0"?>
<!--
Structure of dbc files.
by Mathoshek

Many thanks to:
  http://www.pxr.dk/wowdev/wiki/index.php?title=Main_Page
  https://github.com/mangos/mangos
  https://github.com/TrinityCore/TrinityCore
-->

<DBFilesClient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Structure.xsd">
  
  <table name="Achievement.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="faction" type="int32" />
    <field name="instance_id" type="int32" />
    <field name="supercedes" type="uint32" />
    <field name="title" type="string" />
    <field name="description" type="string" />
    <field name="category" type="uint32" />
    <field name="points" type="uint32" />
    <field name="ui_order" type="uint32" />
    <field name="flags" type="uint32" />
    <field name="iconID" type="uint32" />
    <field name="reward_lang" type="string" />
    <field name="minimum_criteria" type="uint32" />
    <field name="shares_criteria" type="uint32" />
  </table>

  <table name="Achievement_Category.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="parent" type="uint32" />
    <field name="name" type="string" />
    <field name="ui_order" type="uint32" />
  </table>

  <table name="Achievement_Criteria.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="achievement_id" type="uint32" />
    <field name="type" type="uint32" />
    <field name="asset_id" type="uint32" />
    <field name="quantity" type="uint32" />
    <field name="start_event" type="uint32" />
    <field name="start_asset" type="uint32" />
    <field name="fail_event" type="uint32" />
    <field name="fail_asset" type="uint32" />
    <field name="description" type="string" />
    <field name="flags" type="uint32" />
    <field name="timer_start_event" type="uint32" />
    <field name="timer_asset_id" type="uint32" />
    <field name="timer_time" type="uint32" />
    <field name="ui_order" type="uint32" />
    <field name="unk16" type="uint32" />
    <field name="unk17" type="uint32" />
    <field name="unk18" type="uint32" />
    <field name="unk19" type="uint32" />
    <field name="unk20" type="uint32" />
    <field name="unk21" type="uint32" />
    <field name="unk22" type="uint32" />
    <field name="unk23" type="uint32" />
  </table>

  <table name="AnimationData.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="Name" type="string" />
    <field name="Weaponflags" type="uint32" />
    <field name="Bodyflags" type="uint32" />
    <field name="Flags" type="uint32" />
    <field name="Fallback" type="uint32" />
    <field name="BehaviorID" type="uint32" />
    <field name="BehaviorTier" type="uint32" />
  </table>

  <table name="AnimKit.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="oneShotDuration" type="uint32" />
    <field name="oneShotStopAnimKitID" type="uint32" />
  </table>

  <table name="AnimKitBoneSet.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="name" type="string" />
    <field name="boneDataID" type="uint32" />
    <field name="parentAnimKitBoneSetID" type="uint32" />
    <field name="extraBoneCount" type="uint32" />
    <field name="altAnimKitBoneSetID" type="uint32" />
  </table>

  <table name="AnimKitBoneSetAlias.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="boneDataID" type="uint32" />
    <field name="animKitBoneSetID" type="uint32" />
  </table>

  <table name="AnimKitConfig.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="configFlags" type="uint32" />
  </table>

  <table name="AnimKitConfigBoneSet.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="parentAnimKitConfigID" type="uint32" />
    <field name="animKitBoneSetID" type="uint32" />
    <field name="animKitPriorityID" type="uint32" />
  </table>

  <table name="AnimKitPriority.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="priority" type="uint32" />
  </table>

  <table name="AnimKitSegment.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="parentAnimKitID" type="uint32" />
    <field name="animID" type="uint32" />
    <field name="animStartTime" type="uint32" />
    <field name="animKitConfigID" type="uint32" />
    <field name="startCondition" type="uint32" />
    <field name="startConditionParam" type="uint32" />
    <field name="startConditionDelay" type="uint32" />
    <field name="endCondition" type="uint32" />
    <field name="endConditionParam" type="uint32" />
    <field name="endConditionDelay" type="uint32" />
    <field name="speed" type="float" />
    <field name="segmentFlags" type="uint32" />
    <field name="forcedVariation" type="uint32" />
    <field name="overrideConfigFlags" type="uint32" />
    <field name="loopToSegmentIndex" type="uint32" />
  </table>

  <table name="AnimReplacement.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="srcAnimID" type="uint32" />
    <field name="dstAnimID" type="uint32" />
    <field name="parentAnimReplacementSetID" type="uint32" />
  </table>

  <table name="AnimReplacementSet.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="execOrder" type="uint32" />
  </table>

  <table name="AreaAssignment.dbc" primary="generatedID">
    <field name="generatedID" type="uint32" />
    <field name="MapID" type="uint32" />
    <field name="AreaID" type="uint32" />
    <field name="ChunkX" type="uint32" />
    <field name="ChunkY" type="uint32" />
  </table>

  <table name="AreaGroup.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="areaID1" type="uint32" />
    <field name="areaID2" type="uint32" />
    <field name="areaID3" type="uint32" />
    <field name="areaID4" type="uint32" />
    <field name="areaID5" type="uint32" />
    <field name="areaID6" type="uint32" />
    <field name="nextAreaID" type="uint32" />
  </table>

  <table name="AreaPOI.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="importance" type="uint32" />
    <field name="icon1" type="uint32" />
    <field name="icon2" type="uint32" />
    <field name="icon3" type="uint32" />
    <field name="icon4" type="uint32" />
    <field name="icon5" type="uint32" />
    <field name="icon6" type="uint32" />
    <field name="icon7" type="uint32" />
    <field name="icon8" type="uint32" />
    <field name="icon9" type="uint32" />
    <field name="factionID" type="uint32" />
    <field name="x" type="float" />
    <field name="y" type="float" />
    <field name="z" type="float" />
    <field name="continentID" type="uint32" />
    <field name="flags" type="uint32" />
    <field name="areaID" type="uint32" />
    <field name="name" type="string" />
    <field name="description" type="string" />
    <field name="worldStateID" type="uint32" />
    <field name="worldMapLink" type="uint32" />
  </table>

  <!-- AreaPOISortedWorldState -->

  <table name="AreaTable.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="ContinentID" type="uint32" />
    <field name="ParentAreaID" type="uint32" />
    <field name="AreaBit" type="uint32" />
    <field name="flags" type="uint32" />
    <field name="SoundProviderPref" type="uint32" />
    <field name="SoundProviderPrefUnderwater" type="uint32" />
    <field name="AmbienceID" type="uint32" />
    <field name="ZoneMusic" type="uint32" />
    <field name="IntroSound" type="uint32" />
    <field name="ExplorationLevel" type="uint32" />
    <field name="AreaName" type="string" />
    <field name="factionGroupMask" type="uint32" />
    <field name="liquidTypeID1" type="uint32" />
    <field name="liquidTypeID2" type="uint32" />
    <field name="liquidTypeID3" type="uint32" />
    <field name="liquidTypeID4" type="uint32" />
    <field name="minElevation" type="float" />
    <field name="ambient_multiplier" type="float" />
    <field name="lightid" type="uint32" />
    <field name="unk21" type="uint32" />
    <field name="unk22" type="uint32" />
    <field name="unk23" type="uint32" />
    <field name="unk14" type="uint32" />
    <field name="unk25" type="uint32" />
  </table>

  <table name="AreaTrigger.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="ContinentID" type="uint32" />
    <field name="x" type="float" />
    <field name="y" type="float" />
    <field name="z" type="float" />
    <field name="phaseShift" type="uint32" />
    <field name="unk7" type="uint32" />
    <field name="unk8" type="uint32" />
    <field name="radius" type="float" />
    <field name="box_length" type="float" />
    <field name="box_width" type="float" />
    <field name="box_height" type="float" />
    <field name="box_yaw" type="float" />
  </table>

  <table name="ArmorLocation.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="clothmodifier" type="float" />
    <field name="leathermodifier" type="float" />
    <field name="chainmodifier" type="float" />
    <field name="platemodifier" type="float" />
    <field name="modifier" type="float" />
  </table>

  <!-- AttackAnimKits -->

  <!-- AttackAnimTypes -->

  <table name="AuctionHouse.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="factionID" type="uint32" />
    <field name="depositRate" type="uint32" />
    <field name="consignmentRate" type="uint32" />
    <field name="name" type="string" />
  </table>

  <table name="BankBagSlotPrices.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="Cost" type="uint32" />
  </table>

  <table name="BannedAddOns.dbc" primary="ID">
    <field name="ID" type="uint32" />
    <field name="nameMD51" type="uint32" />
    <field name="nameMD52" type="uint32" />
    <field name="nameMD53" type="uint32" />
    <field name="nameMD54" type="uint32" />
    <field name="versionMD51" type="uint32" />
    <field name="versionMD52" type="uint32" />
